<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.28" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ASPNetCoreApp.Tests\**" />
    <Content Remove="ASPNetCoreApp.Tests\**" />
    <EmbeddedResource Remove="ASPNetCoreApp.Tests\**" />
    <None Remove="ASPNetCoreApp.Tests\**" />
  </ItemGroup>

</Project>
